[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
external_node_modules = ["puppeteer-core", "@sparticuz/chromium", "node-fetch", "axios"]
included_files = ["node_modules/@sparticuz/chromium/**"]

[dev]
port = 8888
functions = "netlify/functions"

[build]
functions = "netlify/functions"
publish = "."